name: Publish and Deploy to NuGet

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  release:
    types:
      - published

env:
  NuGetDirectory: ${{github.workspace}}/nuget
  
defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'   # Adjust the .NET SDK version as needed

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      # Handling IpGeoLocationService.Core project
      - name: Update Build Number for Ekzakt.IpGeoLocationService.Core
        run: sed -i "s/\(<Version>\([0-9]\+\.\)\{2\}\)\([0-9]\+\)/\1${{github.run_number}}/" src/Ekzakt.IpGeoLocationService.Core/Ekzakt.IpGeoLocationService.Core.csproj
      
      - name: Pack Ekzakt.IpGeoLocationService.Core
        run: dotnet pack src/Ekzakt.IpGeoLocationService.Core/Ekzakt.IpGeoLocationService.Core.csproj --configuration Release --output ./nupkgs

      # Handling IpGeoLocationService.IpInfo project
      - name: Update Build Number for Ekzakt.IpGeoLocationService.Core
        run: sed -i "s/\(<Version>\([0-9]\+\.\)\{2\}\)\([0-9]\+\)/\1${{github.run_number}}/" src/Ekzakt.IpGeoLocationService.Core/Ekzakt.IpGeoLocationService.Core.csproj
        
      - name: Pack Ekzakt.IpGeoLocationService.IpInfo
        run: dotnet pack src/Ekzakt.IpGeoLocationService.IpInfo/Ekzakt.IpGeoLocationService.IpInfo.csproj --configuration Release --output ./nupkgs

      - name: Publish to NuGet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Publish Core package
        run: dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

      - name: Publish IpInfo package
        run: dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}