name: Publish and Deploy to NuGet

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  release:
    types:
      - published

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Update Build Number and Pack Projects
        run: |
          $offset = 1
          $runNumber = ${{ github.run_number }}
          Write-Host "GitHub run_number: $runNumber"
          $versionNumber = $runNumber - $offset
          Write-Host "Calculated Version Number: $versionNumber"
          $projects = @(
            "src/Ekzakt.IpGeoLocationService.Core/Ekzakt.IpGeoLocationService.Core.csproj",
            "src/Ekzakt.IpGeoLocationService.IpInfo/Ekzakt.IpGeoLocationService.IpInfo.csproj"
          )
          foreach ($project in $projects) {
            sed -i "s/\(<Version>\([0-9]\+\.\)\{2\}\)\([0-9]\+\)/\1$versionNumber/" $project
            dotnet pack $project --configuration Release --output ./nupkgs
          }

      - name: Publish Packages to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
