name: Publish and Deploy to NuGet

on:
  pull_request:
    branches:
      - 'master'
  release:
    types:
      - published

defaults:
  run:
    shell: pwshù
    
jobs:
  create_nuget:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      
    - name: Update Build Number for Ekzakt.IpGeoLocationService.Core
      run: sed -i "s/\(<Version>\([0-9]\+\.\)\{2\}\)\([0-9]\+\)/\1${{github.run_number}}/" ./Ekzakt.IpGeoLocationService.Core/Ekzakt.IpGeoLocationService.Core.csproj
      
    - name: Update Build Number for Ekzakt.IpGeoLocationService.IpInfo
      run: sed -i "s/\(<Version>\([0-9]\+\.\)\{2\}\)\([0-9]\+\)/\1${{github.run_number}}/" ./Ekzakt.IpGeoLocationService.IpInfo/Ekzakt.IpGeoLocationService.IpInfo.csproj
      
    - name: Create NuGet packages for all projects
      run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}